### ISSUE TITLE
UnhandledPromiseRejectionWarning instead of catching `throw new Error()`

### ISSUE THREAD

**Issue by tikonoff** [ericelliott/riteway#134]
Hey Eric, 
thanks for super neat and laconic testing framework!

I have a question about testing async functions.

#### Code
```
export const foo = async (fn, event, cb) => {
  if (!cb) {
    throw new Error('No callback provided!')
  } else {
    try {
      const res = await fn()
      cb(null, res)
    } catch (e) {
      cb(e)
    }
  }
}
```
#### Test
```
describe('foo()', async assert => {
  assert({
    given: 'no callback',
    should: 'throw specific error',
    actual: Try(await responseFormatter(fn, event)),
    expected: Error()
  })
})
```
#### Result
```
foo()
    ✔  Given no function to call: should throw specific error
(node:38228) UnhandledPromiseRejectionWarning: Error: No callback provided!
    at _callee$ (/hmm/src/utils/index.js:3:11)
    at tryCatch (/hmm/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/hmm/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/hmm/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/hmm/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/hmm/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at /hmm/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/hmm/node_modules/core-js/library/modules/_export.js:36:28)
    at /hmm/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:23:12
(node:38228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


  passed: 1,  failed: 0  of 1 tests  (949ms)
```

#### Confusion
it caught the error, but the error was thrown on ` await fn()` call, not on `throw new Error('No callback provided!')`

#### Question
How to catch the Error that I've thrown? 

Thanks!

**Comment by ericelliott** [comment]
Just glancing at the code, it looks like the trouble is that you're attempting to use `Try()` on an async function. `Try()` is designed for functions which throw, but *async functions never throw.*

Instead, when you throw from inside an async function, the result is a rejected promise. To write assertions against rejected promises, try this:

```js
const actual = (await foo().catch(e => e)).message;
const expected = 'No callback provided!';
```
