### ISSUE TITLE
Unwanted details logging during catching an error 

### ISSUE THREAD

**Issue by tikonoff** [ericelliott/riteway#162]
Hey Eric,

recently something changed and now terminal shows errors details when you catching errors.

```
  assert({
    given: 'noRequestId',
    should: 'throw "Missing parameter: requestId"',
    actual: (await newTransfer().catch(e => e)).message,
    expected: 'Missing parameter: requestId'
  })
```

Tests are passed but the output looks messy:

```
Error: Missing parameter: requestId
        at newTransfer (/Users/guest/src/xApi/transfers/transfers.js:19:30)
        at fn (/Users/guest/src/xApi/utils/index.js:23:23)
        at tryCatch (/Users/guest/node_modules/regenerator-runtime/runtime.js:45:40)
        at Generator.invoke [as _invoke] (/Users/guest/node_modules/regenerator-runtime/runtime.js:271:22)
        at Generator.prototype.<computed> [as next] (/Users/guest/node_modules/regenerator-runtime/runtime.js:97:21)
        at asyncGeneratorStep (/Users/guest/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
        at _next (/Users/guest/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
        at /Users/guest/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:34:7
        at new Promise (<anonymous>)
        at new F (/Users/guest/node_modules/core-js/library/modules/_export.js:36:28)    
        
        ✔  Given noRequestId: should throw "Missing parameter: requestId"
```

Is it possible to suppress that?
Thank you.

**Comment by tikonoff** [comment]
It just disappeared by itself. Sorry.
