### ISSUE TITLE
RITEway with CRA: ReferenceError: describe is not defined

### ISSUE THREAD

**Issue by janhesters** [ericelliott/riteway#70]
I'm trying to use RITEway with create-react-app.

I made a new project, installed RITEway via `yarn add --dev` and added `"test": "riteway **/*.test.js | tap-color",` to my `package.json`. (`tap-color` is installed globally on my mac.)

I wanted to write a header using TDD. I wrote a component that should fail all tests:

```js
import React from 'react';

export function Header() {
  return null;
}

export default Header;
```

And wrote the corresponding tests for that:

```js
import React from 'react';
import { describe } from 'riteway';
import render from 'riteway/render-component';

import Header from './';

describe('header', async assert => {
  const $ = render(<Header />);

  assert({
    given: 'just rendering',
    should: "display the string 'rifky'",
    actual: $('header')
      .html()
      .trim(),
    expected: 'rifky'
  });
});
```

But when I run the test via `yarn test` I get the following error:

```bash
/path/to/react/app/rifky/node_modules/is-color-stop/test/index.test.js:6
describe('is-color-stop', function () {
^

ReferenceError: describe is not defined
    at Object.<anonymous> (/path/to/react/app/rifky/node_modules/is-color-stop/test/index.test.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /path/to/react/app/rifky/node_modules/tape/bin/tape:39:9
    at Array.forEach (<anonymous>)
```

Am I missing some configuration? I followed the `README.md` 🤔

**Comment by janhesters** [comment]
Nevermind, the error was because `**/*` looked also inside node modules.
